### ISSUE TITLE
"po4a" breaks UTF-8 chars in the final write out to .md

### ISSUE THREAD

**Issue by eighthave** [mquinson/po4a#201]
Here's the diff between f-droid.org's `./tools/i18n.sh po2md` output vs `PERLLIB=~/code/mquinson/po4a/lib ~/code/mquinson/po4a/po4a --force po/_docs.po4a.conf` (full diff attached [utf8-issues.diff.zip](https://github.com/mquinson/po4a/files/4417902/utf8-issues.diff.zip) ):

```diff
diff -ruw /tmp/_docs/de/All_About_Descriptions_Graphics_and_Screenshots.md _docs/de/All_About_Descriptions_Graphics_and_Screenshots.md
--- /tmp/_docs/de/All_About_Descriptions_Graphics_and_Screenshots.md	2020-04-01 23:50:41.752795076 +0200
+++ _docs/de/All_About_Descriptions_Graphics_and_Screenshots.md	2020-04-01 23:36:51.044896976 +0200
@@ -90,31 +90,31 @@
 
​​ ```
 - <fdroiddata>/
-  └── metadata/
-      └── <package-id>/
-          └── <locale>/
-              ├── full_description.txt
-              ├── short_description.txt
-              ├── title.txt
-              ├── video.txt
-              ├── changelogs/
-              │   ├── <version-code>.txt
-              │   └── <version-code>.txt
-              └── images/
-                  ├── featureGraphic.png
-                  ├── icon.png
-                  ├── promoGraphic.png
-                  ├── tvBanner.png
-                  ├── phoneScreenshots/
-                  │   └── *.png
-                  ├── sevenInchScreenshots/
-                  │   └── *.png
-                  ├── tenInchScreenshots/
-                  │   └── *.png
-                  ├── tvScreenshots/
-                  │   └── *.png
-                  └── wearScreenshots/
-                      └── *.png
+  âââ metadata/
+      âââ <package-id>/
+          âââ <locale>/
+              âââ full_description.txt
+              âââ short_description.txt
+              âââ title.txt
+              âââ video.txt
+              âââ changelogs/
+              â   âââ <version-code>.txt
+              â   âââ <version-code>.txt
+              âââ images/
+                  âââ featureGraphic.png
+                  âââ icon.png
+                  âââ promoGraphic.png
+                  âââ tvBanner.png
+                  âââ phoneScreenshots/
+                  â   âââ *.png
+                  âââ sevenInchScreenshots/
+                  â   âââ *.png
+                  âââ tenInchScreenshots/
+                  â   âââ *.png
+                  âââ tvScreenshots/
+                  â   âââ *.png
+                  âââ wearScreenshots/
+                      âââ *.png
​ ```
 
 Die Bilder müssen entweder JPEGs oder PNGs sein.
```

And the config:

```config
[po4a_langs] de
[po4a_paths] po/_docs.pot $lang:po/_docs.$lang.po

[options] opt:"--addendum-charset=UTF-8"
[options] opt:"--keep=0"
[options] opt:"--localized-charset=UTF-8"
[options] opt:"--master-charset=UTF-8"
[options] opt:"--master-language=en_US"
[options] opt:"--msgmerge-opt='--no-wrap'"
[options] opt:"--porefs=file,wrap"
[options] opt:"--wrap-po=newlines"

[po4a_alias:markdown] text opt:"--option markdown"

[type: markdown] _docs/All_About_Descriptions_Graphics_and_Screenshots.md $lang:_docs/$lang/All_About_Descriptions_Graphics_and_Screenshots.md
[type: markdown] _docs/Anti-Features.md $lang:_docs/$lang/Anti-Features.md
[type: markdown] _docs/Building_Applications.md $lang:_docs/$lang/Building_Applications.md
[type: markdown] _docs/Building_a_Signing_Server.md $lang:_docs/$lang/Building_a_Signing_Server.md
[type: markdown] _docs/Build_Metadata_Reference.md $lang:_docs/$lang/Build_Metadata_Reference.md
[type: markdown] _docs/Build_Server_Setup.md $lang:_docs/$lang/Build_Server_Setup.md
[type: markdown] _docs/Client_Bug_Reports.md $lang:_docs/$lang/Client_Bug_Reports.md
[type: markdown] _docs/Deploying_the_Website.md $lang:_docs/$lang/Deploying_the_Website.md
[type: markdown] _docs/FAQ_-_App_Developers.md $lang:_docs/$lang/FAQ_-_App_Developers.md
[type: markdown] _docs/FAQ_-_Client.md $lang:_docs/$lang/FAQ_-_Client.md
[type: markdown] _docs/FAQ_-_General.md $lang:_docs/$lang/FAQ_-_General.md
[type: markdown] _docs/Feeds.md $lang:_docs/$lang/Feeds.md
[type: markdown] _docs/Getting_logcat_messages_after_crash.md $lang:_docs/$lang/Getting_logcat_messages_after_crash.md
[type: markdown] _docs/How_to_Help.md $lang:_docs/$lang/How_to_Help.md
[type: markdown] _docs/How_to_update_an_app.md $lang:_docs/$lang/How_to_update_an_app.md
[type: markdown] _docs/Importing_Applications.md $lang:_docs/$lang/Importing_Applications.md
[type: markdown] _docs/Inclusion_How-To.md $lang:_docs/$lang/Inclusion_How-To.md
[type: markdown] _docs/Inclusion_Policy.md $lang:_docs/$lang/Inclusion_Policy.md
[type: markdown] _docs/Installing_the_Server_and_Repo_Tools.md $lang:_docs/$lang/Installing_the_Server_and_Repo_Tools.md
[type: markdown] _docs/Maintaining_the_Forum.md $lang:_docs/$lang/Maintaining_the_Forum.md
[type: markdown] _docs/Publishing_Nightly_Builds.md $lang:_docs/$lang/Publishing_Nightly_Builds.md
[type: markdown] _docs/Release_Channels_and_Signing_Keys.md $lang:_docs/$lang/Release_Channels_and_Signing_Keys.md
[type: markdown] _docs/Release_Process.md $lang:_docs/$lang/Release_Process.md
[type: markdown] _docs/Repository_Style_Guide.md $lang:_docs/$lang/Repository_Style_Guide.md
[type: markdown] _docs/Reproducible_Builds.md $lang:_docs/$lang/Reproducible_Builds.md
[type: markdown] _docs/Running_a_Mirror.md $lang:_docs/$lang/Running_a_Mirror.md
[type: markdown] _docs/Security_Model.md $lang:_docs/$lang/Security_Model.md
[type: markdown] _docs/Setup_an_F-Droid_App_Repo.md $lang:_docs/$lang/Setup_an_F-Droid_App_Repo.md
[type: markdown] _docs/Signing_Process.md $lang:_docs/$lang/Signing_Process.md
[type: markdown] _docs/Submitting_to_F-Droid_Quick_Start_Guide.md $lang:_docs/$lang/Submitting_to_F-Droid_Quick_Start_Guide.md
[type: markdown] _docs/Translation_and_Localization.md $lang:_docs/$lang/Translation_and_Localization.md
[type: markdown] _docs/Update_Processing.md $lang:_docs/$lang/Update_Processing.md
[type: markdown] _docs/Verification_Server.md $lang:_docs/$lang/Verification_Server.md
[type: markdown] _docs/Whitelabel_Builds.md $lang:_docs/$lang/Whitelabel_Builds.mdn
```

**Comment by eighthave** [comment]
I should add that these chars all look fine in the original .md, the .pot, and the .de.po.  It is just in the resulting de/.md file that there is corruption.

**Comment by mquinson** [comment]
Is there somewhere where I could play with your data? Or maybe you could provide a tarball with the data?

**Comment by eighthave** [comment]
yes of course!

* The project source code: https://gitlab.com/fdroid/fdroid-website
* My fork: https://gitlab.com/eighthave/fdroid-website/
* command I run: 
`PERLLIB=~/code/mquinson/po4a/lib ~/code/mquinson/po4a/po4a --force --verbose --debug po/_docs.po4a.conf`


Ping me in IRC if you need help with the setup.

**Comment by mquinson** [comment]
You seem to be using the master-language option that you wrote. I'd appreciate if you could submit the patch as a PR, please.

**Comment by mquinson** [comment]
As weird as it may be, I think that nobody ever used po4a with an input in UTF-8. The only tests we have use latin-1 as a charset for the input. This really proves that this soft was almost written in the previous century :sob: 
The good news is that I have a work around. I'll write a small test and commit everything. It may be tomorrow only because it's late already. If you want the fix before the commit, here is the patch, just for you: [patch.txt](https://github.com/mquinson/po4a/files/4441072/patch.txt)

**Comment by eighthave** [comment]
I applied your UTF-8 patch http://paste.debian.net/1138787/ and ran `po4a`:

```console
$ PERLLIB=~/code/mquinson/po4a/lib ~/code/mquinson/po4a/po4a --force --verbose --debug po/_docs.po4a.conf
cmd=[po4a_langs]; main=de; args=""
cmd=[po4a_paths]; main=po/_docs.pot; args="de:po/_docs.de.po "
cmd=[options]; main=opt:"--addendum-charset=UTF-8"; args=""
cmd=[options]; main=opt:"--keep=0"; args=""
cmd=[options]; main=opt:"--localized-charset=UTF-8"; args=""
cmd=[options]; main=opt:"--master-charset=UTF-8"; args=""
cmd=[options]; main=opt:"--master-language=en_US"; args=""
cmd=[options]; main=opt:"--msgmerge-opt='--no-wrap'"; args=""
cmd=[options]; main=opt:"--porefs=file,wrap"; args=""
cmd=[options]; main=opt:"--wrap-po=newlines"; args=""
cmd=[po4a_alias:markdown]; main=text; args="opt:"--option markdown" "
cmd=[type: markdown]; main=_docs/All_About_Descriptions_Graphics_and_Screenshots.md; args="de:_docs/de/All_About_Descriptions_Graphics_and_Screenshots.md "
cmd=[type: markdown]; main=_docs/Anti-Features.md; args="de:_docs/de/Anti-Features.md "
cmd=[type: markdown]; main=_docs/Building_Applications.md; args="de:_docs/de/Building_Applications.md "
cmd=[type: markdown]; main=_docs/Building_a_Signing_Server.md; args="de:_docs/de/Building_a_Signing_Server.md "
cmd=[type: markdown]; main=_docs/Build_Metadata_Reference.md; args="de:_docs/de/Build_Metadata_Reference.md "
cmd=[type: markdown]; main=_docs/Build_Server_Setup.md; args="de:_docs/de/Build_Server_Setup.md "
cmd=[type: markdown]; main=_docs/Client_Bug_Reports.md; args="de:_docs/de/Client_Bug_Reports.md "
cmd=[type: markdown]; main=_docs/Deploying_the_Website.md; args="de:_docs/de/Deploying_the_Website.md "
cmd=[type: markdown]; main=_docs/FAQ_-_App_Developers.md; args="de:_docs/de/FAQ_-_App_Developers.md "
cmd=[type: markdown]; main=_docs/FAQ_-_Client.md; args="de:_docs/de/FAQ_-_Client.md "
cmd=[type: markdown]; main=_docs/FAQ_-_General.md; args="de:_docs/de/FAQ_-_General.md "
cmd=[type: markdown]; main=_docs/Feeds.md; args="de:_docs/de/Feeds.md "
cmd=[type: markdown]; main=_docs/Getting_logcat_messages_after_crash.md; args="de:_docs/de/Getting_logcat_messages_after_crash.md "
cmd=[type: markdown]; main=_docs/How_to_Help.md; args="de:_docs/de/How_to_Help.md "
cmd=[type: markdown]; main=_docs/How_to_update_an_app.md; args="de:_docs/de/How_to_update_an_app.md "
cmd=[type: markdown]; main=_docs/Importing_Applications.md; args="de:_docs/de/Importing_Applications.md "
cmd=[type: markdown]; main=_docs/Inclusion_How-To.md; args="de:_docs/de/Inclusion_How-To.md "
cmd=[type: markdown]; main=_docs/Inclusion_Policy.md; args="de:_docs/de/Inclusion_Policy.md "
cmd=[type: markdown]; main=_docs/Installing_the_Server_and_Repo_Tools.md; args="de:_docs/de/Installing_the_Server_and_Repo_Tools.md "
cmd=[type: markdown]; main=_docs/Maintaining_the_Forum.md; args="de:_docs/de/Maintaining_the_Forum.md "
cmd=[type: markdown]; main=_docs/Publishing_Nightly_Builds.md; args="de:_docs/de/Publishing_Nightly_Builds.md "
cmd=[type: markdown]; main=_docs/Release_Channels_and_Signing_Keys.md; args="de:_docs/de/Release_Channels_and_Signing_Keys.md "
cmd=[type: markdown]; main=_docs/Release_Process.md; args="de:_docs/de/Release_Process.md "
cmd=[type: markdown]; main=_docs/Repository_Style_Guide.md; args="de:_docs/de/Repository_Style_Guide.md "
cmd=[type: markdown]; main=_docs/Reproducible_Builds.md; args="de:_docs/de/Reproducible_Builds.md "
cmd=[type: markdown]; main=_docs/Running_a_Mirror.md; args="de:_docs/de/Running_a_Mirror.md "
cmd=[type: markdown]; main=_docs/Security_Model.md; args="de:_docs/de/Security_Model.md "
cmd=[type: markdown]; main=_docs/Setup_an_F-Droid_App_Repo.md; args="de:_docs/de/Setup_an_F-Droid_App_Repo.md "
cmd=[type: markdown]; main=_docs/Signing_Process.md; args="de:_docs/de/Signing_Process.md "
cmd=[type: markdown]; main=_docs/Submitting_to_F-Droid_Quick_Start_Guide.md; args="de:_docs/de/Submitting_to_F-Droid_Quick_Start_Guide.md "
cmd=[type: markdown]; main=_docs/Translation_and_Localization.md; args="de:_docs/de/Translation_and_Localization.md "
cmd=[type: markdown]; main=_docs/Update_Processing.md; args="de:_docs/de/Update_Processing.md "
cmd=[type: markdown]; main=_docs/Verification_Server.md; args="de:_docs/de/Verification_Server.md "
cmd=[type: markdown]; main=_docs/Whitelabel_Builds.md; args="de:_docs/de/Whitelabel_Builds.md "
Updating po/_docs.pot:
po4a::transtractor::process: Call read(_docs/All_About_Descriptions_Graphics_and_Screenshots.md)
po4a::transtractor::process: Done read(_docs/All_About_Descriptions_Graphics_and_Screenshots.md)
po4a::transtractor::process: Call parse()
Use of uninitialized value $args[0] in sprintf at /home/hans/code/mquinson/po4a/lib/Locale/Po4a/Common.pm line 146.
po4a: Couldn't determine the input document's charset. Please specify it on the command line. (non-ASCII char at )
```

**Comment by eighthave** [comment]
Adding ` opt:"--master-charset=UTF-8"` to the alias made it work:

```
[po4a_alias:markdown] text opt:"--option markdown" opt:"--master-charset=UTF-8"

```

**Comment by eighthave** [comment]
So UTF-8 in the Markdown is working!  But unfortunately, I found a bug in UTF-8 in the YAML Front Matter:

__docs/Translation_and_Localization.md_
```yaml
---
layout: page
title: Translation and Localization
---
```
_po/_docs.pot_
```

#. type: YAML Front Matter: title
#: _docs/Translation_and_Localization.md
#, no-wrap
msgid "Translation and Localization"
msgstr ""
```

_po/_docs.de.po_
```
#. type: YAML Front Matter: title
#: _docs/Translation_and_Localization.md
#, no-wrap
msgid "Translation and Localization"
msgstr "Übersetzung und Lokalisation"
```


__docs/de/Translation_and_Localization.md_
```yaml
---
layout: page
title: "<C3>\x9Cbersetzung und Lokalisation"
---
```

**Comment by mquinson** [comment]
I need the headers of the pot and po files too, please. Also, I'm surprised that it makes any differences whether it's in the YAML part or the regular text part. Is it really the case?
Thx,

**Comment by eighthave** [comment]
*po/_docs.pot*
```
# SOME DESCRIPTIVE TITLE
# Copyright (C) YEAR Free Software Foundation, Inc.
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"POT-Creation-Date: 2020-04-07 14:52+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: en_US\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
```

*po/_docs.de.po*
```
# SOME DESCRIPTIVE TITLE
# Copyright (C) YEAR Free Software Foundation, Inc.
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: team@f-droid.org\n"
"POT-Creation-Date: 2020-04-07 14:52+0200\n"
"PO-Revision-Date: 2020-03-25 16:44+0000\n"
"Last-Translator: C. Rüdinger <Mail-an-CR@web.de>\n"
"Language-Team: German <https://hosted.weblate.org/projects/f-droid/website-docs/de/>\n"
"Language: de\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=n != 1;\n"
"X-Generator: Weblate 4.0-dev\n"
```

Yes, the body of the Markdown is working fine, its just the YAML Front Matter.  This is again in fdroid-website project:

* source: https://gitlab.com/fdroid/fdroid-website/-/blob/master/_docs/Translation_and_Localization.md

* result: https://f-droid.org/de/docs/Translation_and_Localization/

**Comment by eighthave** [comment]
Ok, its weirder than that.  UTF-8 fails entirely in _Translation_and_Localization.md_ but works fine in  _All_About_Descriptions_Graphics_and_Screenshots.md_, so its not YFM-specific.

**Comment by eighthave** [comment]
Ok more weird details:

* when correct it uses `'` quotes: `title: 'Alles über Beschreibungen, Grafiken und Bildschirmfotos'`
* when incorrect it uses `"` quotes: `title: "\x9Cbersetzung und Lokalisation"`
* *_docs/de/Translation_and_Localization.md* is the only translated document that ends up in a non-UTF8 charset, though multiple source documents are ASCII:

```console
$ for f in _docs/*.md; do file $f; done
_docs/All_About_Descriptions_Graphics_and_Screenshots.md: UTF-8 Unicode text
_docs/Anti-Features.md: ASCII text
_docs/Building_Applications.md: UTF-8 Unicode text
_docs/Building_a_Signing_Server.md: ASCII text
_docs/Build_Metadata_Reference.md: UTF-8 Unicode text
_docs/Build_Server_Setup.md: UTF-8 Unicode text, with very long lines
_docs/Client_Bug_Reports.md: ASCII text, with very long lines
_docs/Deploying_the_Website.md: ASCII text, with very long lines
_docs/FAQ_-_App_Developers.md: UTF-8 Unicode text
_docs/FAQ_-_Client.md: ASCII text
_docs/FAQ_-_General.md: ASCII text
_docs/Feeds.md: HTML document, ASCII text, with very long lines
_docs/Getting_logcat_messages_after_crash.md: UTF-8 Unicode text, with very long lines
_docs/How_to_Help.md: ASCII text
_docs/How_to_update_an_app.md: UTF-8 Unicode text
_docs/Importing_Applications.md: UTF-8 Unicode text
_docs/Inclusion_How-To.md: ASCII text
_docs/Inclusion_Policy.md: UTF-8 Unicode text
_docs/Installing_the_Server_and_Repo_Tools.md: UTF-8 Unicode text
_docs/Maintaining_the_Forum.md: ASCII text
_docs/Publishing_Nightly_Builds.md: ASCII text
_docs/Release_Channels_and_Signing_Keys.md: UTF-8 Unicode text
_docs/Release_Process.md: ASCII text
_docs/Repository_Style_Guide.md: UTF-8 Unicode text
_docs/Reproducible_Builds.md: ASCII text
_docs/Running_a_Mirror.md: ASCII text, with very long lines
_docs/Security_Model.md: UTF-8 Unicode text
_docs/Setup_an_F-Droid_App_Repo.md: UTF-8 Unicode text
_docs/Signing_Process.md: UTF-8 Unicode text
_docs/Submitting_to_F-Droid_Quick_Start_Guide.md: ASCII text
_docs/Translation_and_Localization.md: ASCII text
_docs/Update_Processing.md: UTF-8 Unicode text
_docs/Verification_Server.md: ASCII text
_docs/Whitelabel_Builds.md: exported SGML document, ASCII text, with very long lines
$ for f in _docs/de/*.md; do file $f; done
_docs/de/All_About_Descriptions_Graphics_and_Screenshots.md: UTF-8 Unicode text
_docs/de/Anti-Features.md: UTF-8 Unicode text
_docs/de/Building_Applications.md: UTF-8 Unicode text
_docs/de/Building_a_Signing_Server.md: UTF-8 Unicode text
_docs/de/Build_Metadata_Reference.md: UTF-8 Unicode text, with very long lines
_docs/de/Build_Server_Setup.md: UTF-8 Unicode text
_docs/de/Client_Bug_Reports.md: UTF-8 Unicode text
_docs/de/Deploying_the_Website.md: UTF-8 Unicode text, with very long lines
_docs/de/FAQ_-_App_Developers.md: UTF-8 Unicode text
_docs/de/FAQ_-_Client.md: UTF-8 Unicode text
_docs/de/FAQ_-_General.md: UTF-8 Unicode text
_docs/de/Feeds.md: HTML document, UTF-8 Unicode text
_docs/de/Getting_logcat_messages_after_crash.md: UTF-8 Unicode text
_docs/de/How_to_Help.md: UTF-8 Unicode text
_docs/de/How_to_update_an_app.md: UTF-8 Unicode text
_docs/de/Importing_Applications.md: UTF-8 Unicode text
_docs/de/Inclusion_How-To.md: UTF-8 Unicode text
_docs/de/Inclusion_Policy.md: UTF-8 Unicode text
_docs/de/Installing_the_Server_and_Repo_Tools.md: UTF-8 Unicode text
_docs/de/Maintaining_the_Forum.md: UTF-8 Unicode text
_docs/de/Publishing_Nightly_Builds.md: UTF-8 Unicode text
_docs/de/Release_Channels_and_Signing_Keys.md: UTF-8 Unicode text
_docs/de/Release_Process.md: UTF-8 Unicode text
_docs/de/Repository_Style_Guide.md: UTF-8 Unicode text
_docs/de/Reproducible_Builds.md: UTF-8 Unicode text
_docs/de/Running_a_Mirror.md: UTF-8 Unicode text
_docs/de/Security_Model.md: UTF-8 Unicode text
_docs/de/Setup_an_F-Droid_App_Repo.md: UTF-8 Unicode text
_docs/de/Signing_Process.md: UTF-8 Unicode text
_docs/de/Submitting_to_F-Droid_Quick_Start_Guide.md: UTF-8 Unicode text
_docs/de/Translation_and_Localization.md: Non-ISO extended-ASCII text
_docs/de/Update_Processing.md: UTF-8 Unicode text
_docs/de/Verification_Server.md: UTF-8 Unicode text
_docs/de/Whitelabel_Builds.md: exported SGML document, UTF-8 Unicode text, with very long lines

```

**Comment by mquinson** [comment]
Ok. That's actually a good news, because the YFM is parsed exactly as the rest of the markdown document. I've added a specific bunch of regular expressions to open the YFM and inject it back to the document and po files.

I think that what is at stake is that internally, po4a tries to use ascii unless proven wrong. This is what hapened in the bug I fixed: the file was encoded in UTF, but trying to read it as ascii was not leading to any problem (any UTF chars could be decomposed into printable ascii chars, leading po4a to think that it was valid ascii chars). 

I fixed the previous problem by asking po4a to not assume that it was ascii, and being a bit more agressive to try using UTF instead. It seems that I need to be even more agressive and change po4a to use UTF in any case (unless explicitely asked otherwise).

**Comment by eighthave** [comment]
I don't know what might break, but I suppose UTF-8 by default, it really is a well established, widespread standard encoding at this point.

**Comment by eighthave** [comment]
There are three other Markdown files in the website where this happens:
```console
 $ for f in _*/de/*.md; do file $f; done|grep -v UTF
_docs/de/Translation_and_Localization.md: Non-ISO extended-ASCII text
_pages/de/about.md: Non-ISO extended-ASCII text
_posts/de/2018-09-03-replacing-gcm-in-tutanota.md: exported SGML document, Non-ISO extended-ASCII text
_posts/de/2019-07-06-improving-our-bus-factor.md: Non-ISO extended-ASCII text
```

**Comment by mquinson** [comment]
On Tue, Apr 07, 2020 at 09:27:49AM -0700, Hans-Christoph Steiner wrote:
> I don't know what might break, but I support UTF-8 by default, it really is a well established, widespread standard encoding at this point.

I think I couldn't agree more.

I just need to find the time to implement this. I was hoping to save
some time with the lockdown, but remoting is also time-consuming...

**Comment by eighthave** [comment]
The source documents for these two are ASCII:
* _docs/de/Translation_and_Localization.md: Non-ISO extended-ASCII text
* _posts/de/2019-07-06-improving-our-bus-factor.md: Non-ISO extended-ASCII text

The source documents for these two are UTF-8:
* _pages/de/about.md: Non-ISO extended-ASCII text
* _posts/de/2018-09-03-replacing-gcm-in-tutanota.md: exported SGML document, Non-ISO extended-ASCII text

In the corrupted documents that are from a UTF-8 source file, the corruption only shows up in the YAML Front Matter.  In the corrupted documents that are from an ASCII source file, the corruption shows up for all unicode characters throughout the document.

**Comment by mquinson** [comment]
Ok, I think that your bug is fixed in the current git. Could you please confirm?

**Comment by eighthave** [comment]
The newest commit fixed the corruption in the Markdown text, but the corruption still happens sometimes in the YAML Front Matter.

**Comment by eighthave** [comment]
For example, for *_pages/de/about.md*, it currently generates:
```yaml
title: "<C3>\x9Cber"
```
While *po/_pages.de.po* has:
```gettext
#. type: Title #
#: build/_pages/md/about.md
#, no-wrap
msgid "About"
msgstr "Über"
````

**Comment by eighthave** [comment]
It worked! https://gitlab.com/eighthave/fdroid-website/-/jobs/507895633  I'll test more tomorrow

**Comment by erciccione** [comment]
I am having a similar problem when running

```
po4a-gettextize -f text -m {markdown source file} -l {markdown localized file} -p {new po}
```

The translated markdown file is UTF-8, the resulting .po file seems to have recognized the encoding `"Content-Type: text/plain; charset=UTF-8\n"`, but german-specific characters like `ö` are showing as `�`. I tried playing with encoding and other changes with no success. I get `Use of uninitialized value $newchar in substitution iterator at /usr/share/perl5/vendor_perl/Locale/Po4a/Po.pm line 1619.` after running the command i specified above, but i don't know if that's related to this issue.

Did i miss something or there is a problem somewhere?

po4a-gettextize version 0.61

**Comment by eighthave** [comment]
I'm using po4a 0.61 and it works with UTF-8 for f-droid.org.  We are not using `po4a-gettextize` though
